Repository chaosblade-io/chaosblade, pull requests merged in 2019-04, with the labels that each got.

#20 refactor: change service-port to local-port and invoke-port to remote…
  exec/os/bin/delaynetwork.go
  exec/os/bin/dropnetwork.go
  exec/os/bin/lossnetwork.go
  exec/os/network_delay.go
  exec/os/network_drop.go
  exec/os/network_loss.go
Labels: enhancement

#35 refactor: unify the disk experiment flag name and add value judgment
  exec/os/bin/burnio.go
  exec/os/bin/filldisk.go
  exec/os/disk.go
  exec/os/disk_burn.go
  exec/os/disk_fill.go
  util/util_test.go
Labels: kind/enhancement

#38 bugfix: fix destroy experiment is delete k8s pod error
  exec/kubernetes/spec_delete.go
Labels: bug

#47 Update Dockerfile
  Dockerfile
Labels: kind/bug

#54 bugfix: fix --numcpu parameter strong check
  exec/os/cpu.go
Labels: kind/bug
