Repository chaosblade-io/chaosblade, pull requests merged in 2019-07, with the labels that each got.

#112 feature: add travis CI service
  .travis.yml
  Makefile
  exec/kubernetes/channel_test.go
  exec/os/bin/burncpu/burncpu.go
  exec/os/bin/burnio/burnio.go
  exec/os/bin/changedns/changedns.go
  exec/os/bin/common.go
  exec/os/bin/delaynetwork/delaynetwork.go
  exec/os/bin/dropnetwork/dropnetwork.go
  exec/os/bin/filldisk/filldisk.go
  exec/os/bin/killprocess/killprocess.go
  exec/os/bin/lossnetwork/lossnetwork.go
Labels: kind/enhancement

#140 feature: add --port args for jvm preparation
  cli/prepare_jvm.go
  cli/revoke.go
  exec/jvm/sandbox.go
Labels: enhancement

#141 bugfix: change command output from stderr to stdout when command exec…
  cli/cli.go
Labels: kind/bug

#142 feature: add support for cplus executor
  Makefile
  cli/exp.go
  cli/main.go
  cli/prepare.go
  cli/prepare_cplus.go
  cli/prepare_jvm.go
  cli/prepare_test.go
  cli/revoke.go
  exec/cplus/cplus.go
  exec/cplus/executor.go
  transport/response.go
  util/util.go
Labels: kind/feature

#146 feature: add quick works support for disk fill
  exec/os/bin/filldisk/filldisk.go
Labels: kind/enhancement
