Repository chaosblade-io/chaosblade, pull requests merged in 2025-09, with the labels that each got.

#1136 Chore: Synchronize Makefile and go.mod branch versions
  Makefile
  docs/version_sync_guide.md
  go.mod
  go.sum
  scripts/sync_go_mod.sh
  version/version_info.go
Labels: chaosblade-cli

#1147 Bugfix: Solve the problem of command failure in container scenario
  nsexec.c
Labels: type/bug, chaosblade-cli

#1185 feat: Supports accessing the cluster through kubectl-proxy
  cli/cmd/destroy.go
  cli/cmd/query_k8s.go
  exec/kubernetes/executor.go
  exec/kubernetes/spec.go
  version/version_info.go
Labels: type/feature

#1189 feat: Support specifying chaosblade data file path
  data/source.go
  data/source_test.go
  go.mod
  go.sum
Labels: type/enhancement

#1219 chore: update and reformat MAINTAINERS.md
  MAINTAINERS.md
Labels: project governance
